import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Contact.module.css'
import Menu from "@/components/Menu/index.js";
import Grad from "@/components/Grad/index.js";
import uparrow from "@/public/icons/upwardArrow.png";
import Background from "@/public/background-images/backgroundMountainUpsideDown.jpg";
import { useState } from "react";

export default function Contact() {
    const [formData, setFormData] = useState({
        first: "",
        firstWarning: "",
        last: "",
        lastWarning: "",
        email: "",
        emailWarning: ""
    });

    const { first, firstWarning, last, lastWarning, email, emailWarning } = formData;

    function First(event) {
        var input = event.target.value;
        const validater = new RegExp(/^[a-z]/);
        if (validater.test(input) == true) {
            setFormData({
                ...formData,
                first: input,
                firstWarning: "First Name error. First Letter must be capital. Must use alphabets only"
            });
        } else if (validater.test(input) == false) {
            setFormData({ ...formData, first: input, firstWarning: "" });
        }
    }

    function Last(event) {
        var input = event.target.value;
        const validater = new RegExp(/^[a-z]/);
        if (validater.test(input) == true) {
            setFormData({
                ...formData,
                last: input,
                lastWarning: "Last Name error. Last Letter must be capital. Must use alphabets only"
            });
        } else if (validater.test(input) == false) {
            setFormData({ ...formData, last: input, lastWarning: "" });
        }
    }

    function Email(event) {
        var input = event.target.value;
        const validater = new RegExp(/^[\w-.]+@([\w-]+.)+[\w-]{2,4}$/);

        if (validater.test(input) == false) {
            setFormData({ ...formData, email: input, emailWarning: "Email is Invalid" });
        } else if (validater.test(input) == true) {
            setFormData({ ...formData, email: input, emailWarning: "" });
        }
    }
    return (
        <>
            <Head>
                <title>Contact Us</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name="author" content="MDIA 2109" />
                <meta property='og:title' content="Assignment #1 - Contact Us Page" />
                <meta property='og:description' content="BCIT Digital Design and Development Diploma" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <main className={styles.main}>
                <Image
                    src={Background}
                    fill
                    style={{
                        zIndex: -10,
                    }}
                />

                <div className={styles.header}>
                    <Menu></Menu>
                    <Grad></Grad>
                </div>

                <div className={styles.contact_content}>
                    <div className={styles.contact_title}>
                        <div></div>
                        <h1 className={styles.contact_name}>Contact Us</h1>
                        <div></div>
                    </div>

                    <div className={styles.contact_box}>
                        <p>Want to discuss? Lets chat!</p>
                        <div className={styles.container}>
                            <form className={styles.form}>
                                <fieldset className={styles.fieldset}>
                                    <table className={styles.table}>
                                        <thead className={styles.top}>
                                            <tr className={styles.first_row}>
                                                <td>
                                                    <div>
                                                        <h4>First Name:</h4>
                                                        <input
                                                            placeholder="First Name Here"
                                                            value={first}
                                                            onChange={First}
                                                        ></input>
                                                    </div>
                                                    <div>
                                                        <h4>Last Name:</h4>
                                                        <input
                                                            placeholder="Last Name Here"
                                                            value={last}
                                                            onChange={Last}
                                                        ></input>
                                                    </div>
                                                </td>
                                            </tr>
                                        </thead>
                                        <thead className={styles.bottom}>
                                            <tr className={styles.second_row}>
                                                <td>
                                                    <div>
                                                        <h4>Email:</h4>
                                                        <input
                                                            placeholder="Email Here"
                                                            value={email}
                                                            onChange={Email}
                                                        ></input>
                                                    </div>
                                                </td>
                                            </tr>
                                        </thead>
                                    </table>
                                </fieldset>
                                <div className={styles.feedback}>
                                    <div className={styles.warnings}>
                                        <p>{firstWarning}</p>
                                        <p>{lastWarning}</p>
                                        <p>{emailWarning}</p>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <a href="/about">
                    <span>
                        <Image src={uparrow} className={styles.arrow} />
                    </span>
                </a>
            </main>
        </>
    )
}
